### ISSUE TITLE
Key Exchange methods of libsodium

### ISSUE THREAD

**Issue by JustADevGuy** [soatok/rawr-x3dh#4]
Dear Soatok,

first of all, thanks for your library and the really great blog article. I'm currently trying to learn more about encryption and your blog post together with this repo is a really helpful example.

I just have one question: Although I understand the reasons why you are using ED25519 instead of X25519, wouldn't replacing the ```crypto_sign_keypair``` function with the ```crypto_kx_keypair``` method provide the use of X25519? Why did you choose not to use ```crypto_kx_keypair```?

Thanks a lot for your help!

EDIT: I just saw that in your blog post you are using ```crypto_box_keypair``` which is actually a X25519 - why did you switch back to ```crypto_sign_keypair``` then?

**Comment by soatok** [comment]
> Why did you choose not to use `crypto_kx_keypair`?

[To piggyback on an existing protocol for distributing Ed25519 keys](https://soatok.blog/2020/11/14/going-bark-a-furrys-guide-to-end-to-end-encryption/#identity-key-management).

You can [go from Ed25519 to X25519](https://doc.libsodium.org/advanced/ed25519-curve25519). The reverse is not possible (due to the SHA512 step in Ed25519).

Signal uses X25519 keys instead of Ed25519 keys, and had to build their own X25519-based signature algorithm. It works but it's ugly.

**Comment by JustADevGuy** [comment]
Thanks a lot! That makes sense.
